name = "ThresholdFreeClusterEnhancement"
uuid = "ab421cc8-e01b-5675-99c3-7bb45ba48198"
authors = ["Benedikt Ehinger <tfce@benediktehinger.de>"]
version = "0.1.0"

[workspace]
projects = ["test", "docs", "benchmark"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
LinearAlgebra = "1.10"
julia = "1.10"
